export const UPDATE_DB = 'UPDATE_DB';
export const UPDATE_SURVIVOR_STORE = 'UPDATE_SURVIVOR_STORE';
export const DELETE_SURVIVOR_STORE = 'DELETE_SURVIVOR_STORE';
export const ADD_SURVIVOR_STORE = 'ADD_SURVIVOR_STORE';
export const SET_LOADING = 'SET_LOADING';